version: '3'

volumes:
  blogsapp_local_postgres_data: {}
  blogsapp_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: blogsapp_local_django
    container_name: blogsapp_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: blogsapp_production_postgres
    container_name: blogsapp_local_postgres
    volumes:
      - blogsapp_local_postgres_data:/var/lib/postgresql/data:Z
      - blogsapp_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

#  docs:
#    image: blogsapp_local_docs
#    container_name: blogsapp_local_docs
#    platform: linux/x86_64
#    build:
#      context: .
#      dockerfile: ./compose/local/docs/Dockerfile
#    env_file:
#      - ./.envs/.local/.django
#    volumes:
#      - ./docs:/docs:z
#      - ./config:/app/config:z
#      - ./blogsapp:/app/blogsapp:z
#    ports:
#      - "9000:9000"
#    command: /start-docs
